### ISSUE TITLE
91. Decode Ways

### ISSUE THREAD

**Issue by gh4abhi** [Arsh069/Daily_Challenges#16]
Leetcode Problem - 91. Decode Ways
Problem Link - https://leetcode.com/problems/decode-ways/

**Comment by Vishwa-docs** [comment]
I am working on this

**Comment by gh4abhi** [comment]
@Vishwa-docs I have solved this problem in C++. You can add the solution of the same problem in some other language.

**Comment by Vishwa-docs** [comment]
ok, I will add it in java
How do I submit the solution to the same?
